baseURL = 'https://samh.fyi/'
languageCode = 'en-us'
title = 'samh'
theme = 'paper'

canonifyURLs = true

[params]
  color = 'linen'                           # linen, wheat, gray, light
  github = 'samhardeman'
  bio = 'welcome!'

  monoDarkIcon = true 

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10
  [[menus.main]]
    name = 'Books'
    pageRef = '/books'
    weight = 20
  [[menus.main]]
    name = 'Bits and Pieces'
    pageRef = '/bits-and-pieces'
    weight = 30
  [[menus.main]]
    name = 'Notes'
    pageRef = '/notes'
    weight = 40
    